name: wordle
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  english_words: ^4.0.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  google_fonts: ^6.1.0
  pinput: ^3.0.1
  stroke_text: ^0.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
